### PR TITLE
My Node Class

### PR DESCRIPTION
**Pull request by Lucretian**
This contains the node class I got down in class and my comments.

### CODE REVIEW

**Comment by learner-long-life** [comment]
Thanks @Lucretian 
@HiraethAwaits @JonahEadieEvergreen can you take a look at these commits and provide comments?

**Review by de02E — CHANGES_REQUESTED** [review]
Remove git-config.sh from the pull request as this is the monorepo.

**Comment by learner-long-life** [comment]
@de02E bump. It looks like your requested change was made. Does everything look good for @Lucretian  merge?

I think it's okay if there is one other unrelated change from `HashMapWrapper` for now, it got pulled from `main` I think.

**Review by HiraethAwaits — APPROVED** [review]

**Review by de02E — APPROVED** [review]
Looks good to me!

**Review by learner-long-life — APPROVED** [review]
This appeared on main and got merged some other way. It's been useful in work on LinkedLists and going forward.

**Comment by learner-long-life** [comment]
Not merging, the Node changes made it onto `main` some other way. There are some conflicts and other changes got picked up for HashMapWrapper that are hard to resolve on the web.

**Pull request closed without merging**
