### PR TITLE
fix to put pixels in row-based order

### PR DESCRIPTION
**Pull request by WinstonShine**

### CODE REVIEW

**Comment by WinstonShine** [comment]
The only change was on line 20 where I swapped x and y when indexing into the image data.
everything else was formatting.
Also commented out network code temporarily so this could be tested.

**Comment by learner-long-life** [comment]
This looks good, have you tested it?

**Review by learner-long-life — CHANGES_REQUESTED** [review]
There are a few whitespace changes at the ends of lines, maybe run a linter?
That would improve a lot of the original "style" too. Thanks for doing this.

**Comment by learner-long-life** [comment]
I tested it, it works.

**Pull request merged**
