### PR TITLE
Add Lesson Plans for Monday 2023-10-09.md

### PR DESCRIPTION
**Pull request by learner-long-life**

### CODE REVIEW

**Review by weissri — COMMENTED** [review]
what examples will you use?

**Comment by AbyssalRemark** [comment]
Id be curious what you plan on doing for Algorithm analysis and Resource Usage. I would think this would be about memory usage vs time complexity.  Like how we often add a last pointer to a linked list for easier insertion.  Saves time at the cost of memory.  That sort of thing. But from your comments earlier today It sounds like it might be the start of talking about big O? 

If it were me Id want to talk about profiling tools a little.  Though I don't know what that looks like in terms of java. That might be a little too advanced or out of scope of the class. But its at the very least worth mentioning.  I know its something I care to learn about more and with this class seeming to really want to emphasizes a  what a real working environment looks like It seems like a natural thing to get to, at least at some point.

**Comment by learner-long-life** [comment]
> what examples will you use?

For algorithm analysis, I was considering the metaphor of a road trip, or more probably, a moving van.
Moving with a van or U-Haul takes time, and the vehicle has a certain amount of weight it can haul.
These are like computational time and space for an algorithm to run.
They also consume fuel or electricity, which is a metaphor for computers using energy as well.
You can trade off with renting a smaller / cheaper moving van, but it will have less space and you'll have to make more trips to move the same amount of stuff. You can also rent a bigger / more expensive vehicle to make fewer trips. The amount of stuff you have to move can be the dataset you want to process. For big corporate moves, you can also rent a fleet of vans to move in parallel.

Another metaphor is using the restaurant kitchen metaphor. If a kitchen is well laid out, you can cook certain dishes quickly, but you have to choose a limited number of dishes and specialize in them if you value efficiency. (Early McDonald's founders ran endless tests to optimize their kitchen layout for hamburgers and fries). If you need to cook a lot of food and serve a lot of people, you can choose to have a larger, higher-rent kitchen to decrease cooking time, or you can rent a smaller, cheaper kitchen if the customers consider a longer cooking time acceptable or a plus (consider gourmet or Michelin-star restaurants). A larger kitchen usually implies hiring more staff / cooks, in analogy to a large data structure implying multiple cores and parallel processing at a certain point.

**Comment by learner-long-life** [comment]
> Id be curious what you plan on doing for Algorithm analysis and Resource Usage. I would think this would be about memory usage vs time complexity. Like how we often add a last pointer to a linked list for easier insertion. Saves time at the cost of memory. That sort of thing. But from your comments earlier today It sounds like it might be the start of talking about big O?
> 
> If it were me Id want to talk about profiling tools a little. Though I don't know what that looks like in terms of java. That might be a little too advanced or out of scope of the class. But its at the very least worth mentioning. I know its something I care to learn about more and with this class seeming to really want to emphasizes a what a real working environment looks like It seems like a natural thing to get to, at least at some point.

Yes, we'll definitely be talking about Knuth's Big-Oh notation which is connected to time-space tradeoffs. The last pointer in a linked list is a good example. We add a constant amount of space to save a linear amount of time to add to the end of a linked list. If you can speed up any operation more than a constant amount of time, for a constant increase in space (usually a finite number of integers) it is almost always worth it.

Profiling tools are a good idea. For the GraalVM, the VisualVM tool appears to be used often to display heap usage and other stats. However, I'm still figuring out how to run this in GitPod in a way that fits into our tech stack so far. Your and everyone's feedback or joint research is welcome.

This seems a promising place to start
https://www.graalvm.org/latest/tools/profiling/

**Pull request merged**
